const data={
     products:[
          {
               _id:'1',
               name: 'Nike Slim Shirt',
               category: 'Shirt',
               image:'/Image/p1.jpg',
               price: 120,
               countInStock:10,
               brand: 'Nike',
               rating: 4.5,
               numReviews: 10,
               description: 'high quality product',
          },
          {
               _id:'2',
               name: 'Adidas Slim Shirt',
               category: 'Shirt',
               image:'/Image/p2.jpg',
               price: 120,
               countInStock:20,
               brand: 'Adidas',
               rating: 4.5,
               numReviews: 10,
               description: 'high quality product',
          },
          {
               _id:'3',
               name: 'Lacoste Slim Shirt',
               category: 'Shirt',
               image:'/Image/p3.jpg',
               price: 220,
               countInStock:15,
               brand: 'Nike',
               rating: 4,
               numReviews: 10,
               description: 'high quality product',
          },
          {
               _id:'4',
               name: 'Nike Slim Pant',
               category: 'Pansts',
               image:'/Image/p4.jpg',
               price: 20,
               countInStock:5,
               brand: 'Nike',
               rating: 4.5,
               numReviews: 10,
               description: 'high quality product',
          },
          {
               _id:'5',
               name: 'Adidas Slim Pant',
               category: 'Pants',
               image:'/Image/p5.jpg',
               price: 120,
               countInStock:25,
               brand: 'Nike',
               rating: 4.5,
               numReviews: 10,
               description: 'high quality product',
          },
          {
               _id:'6',
               name: 'Lacoste Slim Pant',
               category: 'Pants',
               image:'/Image/p6.jpg',
               price: 120,
               brand: 'Nike',
               rating: 4.5,
               numReviews: 10,
               description: 'high quality product',
          },
          
     ],
};

export default data;